export default[
        "Database Systems II",
        "Numerical Analysis",
        "Technical Report Writing",
        "Object Oriented Programming II",
        "Applied Electronics",
        "Modeling and Simulation",
        "Data Communication & Protocols",
        "Computer Security",
        "Artificial Intelligence",
        "Distributed systems",
        "Linear Algebra II",
        "Information & Computer Networks Security",
        "Management Information Systems",
        "Mathematical Analysis II",
        "Structured Programming",
        "Computer Skills",
        "Geographical Information Systems",
        "Internet Information Systems",
        "Linear & Integer Programming",
        "Decision Support Systems",
        "Image Processing",
        "Pattern Recognition",
        "Theory of Computation",
        "Algorithms and Data  Structures",
        "File Organization & Processing",
        "Logic Programming",
        "Internet Technologies",
        "Communication Technology",
        "Analysis and Design of Information Systems I"
]